/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Box001: THREE.Mesh
  }
  materials: {
    ['fallback Material']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.508, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Box001.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
